set_property IOSTANDARD LVCMOS25 [get_ports trx0_iic_scl_io]
set_property IOSTANDARD LVCMOS25 [get_ports trx0_iic_sda_io]
set_property IOSTANDARD LVCMOS25 [get_ports trx0_rxrst_o]
set_property IOSTANDARD LVCMOS25 [get_ports trx0_rxdcbal_o]
set_property IOSTANDARD LVCMOS25 [get_ports trx1_rxrst_o]
set_property IOSTANDARD LVCMOS25 [get_ports trx1_rxdcbal_o]
set_property IOSTANDARD LVCMOS25 [get_ports trx1_txrst_o]
set_property IOSTANDARD LVCMOS25 [get_ports trx1_txdcbal_o]
set_property IOSTANDARD LVCMOS25 [get_ports trx1_iic_scl_io]
set_property IOSTANDARD LVCMOS25 [get_ports trx1_iic_sda_io]
set_property IOSTANDARD LVDS_25 [get_ports trx0_rxclk_p_i]
set_property IOSTANDARD LVDS_25 [get_ports trx0_rxclk_n_i]
set_property IOSTANDARD LVDS_25 [get_ports trx0_txclk_p_o]
set_property IOSTANDARD LVDS_25 [get_ports trx0_txclk_n_o]
set_property IOSTANDARD LVCMOS25 [get_ports trx0_txrst_o]
set_property IOSTANDARD LVCMOS25 [get_ports trx0_txdcbal_o]
set_property IOSTANDARD LVDS_25 [get_ports trx1_rxclk_p_i]
set_property IOSTANDARD LVDS_25 [get_ports trx1_rxclk_n_i]
set_property IOSTANDARD LVCMOS25 [get_ports trx0_rxlock_i]
set_property IOSTANDARD LVCMOS25 [get_ports trx0_txlock_i]
set_property IOSTANDARD LVCMOS25 [get_ports trx1_rxlock_i]
set_property IOSTANDARD LVCMOS25 [get_ports trx1_txlock_i]
set_property IOSTANDARD LVDS_25 [get_ports trx1_clk_p_i]
set_property IOSTANDARD LVDS_25 [get_ports trx1_clk_n_i]
set_property IOSTANDARD LVDS_25 [get_ports {trx0_rxdata_p_i[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx0_rxdata_n_i[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx0_rxdata_p_i[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx0_rxdata_n_i[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx0_rxdata_p_i[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx0_rxdata_n_i[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx0_txdata_p_o[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx0_txdata_n_o[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx0_txdata_p_o[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx0_txdata_n_o[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx1_rxdata_p_i[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx1_rxdata_n_i[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx1_rxdata_p_i[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx1_rxdata_n_i[3]}]
set_property IOSTANDARD LVDS_25 [get_ports trx1_txclk_p_o]
set_property IOSTANDARD LVDS_25 [get_ports trx1_txclk_n_o]
set_property IOSTANDARD LVDS_25 [get_ports {trx1_txdata_p_o[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx1_txdata_n_o[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx1_txdata_p_o[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx1_txdata_n_o[3]}]
set_property IOSTANDARD LVDS_25 [get_ports trx0_clk_p_i]
set_property IOSTANDARD LVDS_25 [get_ports trx0_clk_n_i]
set_property IOSTANDARD LVDS_25 [get_ports {trx0_rxdata_p_i[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx0_rxdata_n_i[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx0_rxdata_p_i[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx0_rxdata_n_i[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx0_txdata_p_o[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx0_txdata_n_o[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx0_txdata_p_o[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx0_txdata_n_o[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx0_txdata_p_o[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx0_txdata_n_o[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx1_rxdata_p_i[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx1_rxdata_n_i[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx1_rxdata_p_i[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx1_rxdata_n_i[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx1_rxdata_p_i[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx1_rxdata_n_i[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx1_txdata_p_o[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx1_txdata_n_o[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx1_txdata_p_o[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx1_txdata_n_o[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx1_txdata_p_o[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {trx1_txdata_n_o[4]}]


set_property PACKAGE_PIN L21 [get_ports trx0_iic_scl_io]
set_property PACKAGE_PIN L22 [get_ports trx0_iic_sda_io]
set_property PACKAGE_PIN R19 [get_ports trx0_rxrst_o]
set_property PACKAGE_PIN T19 [get_ports trx0_rxdcbal_o]
set_property PACKAGE_PIN K19 [get_ports trx1_rxrst_o]
set_property PACKAGE_PIN K20 [get_ports trx1_rxdcbal_o]
set_property PACKAGE_PIN D20 [get_ports trx1_txrst_o]
set_property PACKAGE_PIN C20 [get_ports trx1_txdcbal_o]
set_property PACKAGE_PIN E21 [get_ports trx1_iic_scl_io]
set_property PACKAGE_PIN D21 [get_ports trx1_iic_sda_io]
set_property PACKAGE_PIN N20 [get_ports trx0_rxclk_n_i]
set_property PACKAGE_PIN K18 [get_ports trx0_txclk_n_o]
set_property PACKAGE_PIN L17 [get_ports trx0_txrst_o]
set_property PACKAGE_PIN M17 [get_ports trx0_txdcbal_o]
set_property PACKAGE_PIN B20 [get_ports trx1_rxclk_n_i]
set_property PACKAGE_PIN E15 [get_ports trx0_rxlock_i]
set_property PACKAGE_PIN D15 [get_ports trx0_txlock_i]
set_property PACKAGE_PIN F18 [get_ports trx1_rxlock_i]
set_property PACKAGE_PIN E18 [get_ports trx1_txlock_i]
set_property PACKAGE_PIN C19 [get_ports trx1_clk_n_i]
set_property PACKAGE_PIN M20 [get_ports {trx0_rxdata_n_i[0]}]
set_property PACKAGE_PIN P22 [get_ports {trx0_rxdata_n_i[2]}]
set_property PACKAGE_PIN J22 [get_ports {trx0_rxdata_n_i[4]}]
set_property PACKAGE_PIN P21 [get_ports {trx0_txdata_n_o[1]}]
set_property PACKAGE_PIN K21 [get_ports {trx0_txdata_n_o[3]}]
set_property PACKAGE_PIN F19 [get_ports {trx1_rxdata_n_i[1]}]
set_property PACKAGE_PIN C22 [get_ports {trx1_rxdata_n_i[3]}]
set_property PACKAGE_PIN C18 [get_ports trx1_txclk_n_o]
set_property PACKAGE_PIN B17 [get_ports {trx1_txdata_n_o[1]}]
set_property PACKAGE_PIN B22 [get_ports {trx1_txdata_n_o[3]}]
set_property PACKAGE_PIN L19 [get_ports trx0_clk_n_i]
set_property PACKAGE_PIN P18 [get_ports {trx0_rxdata_n_i[1]}]
set_property PACKAGE_PIN M22 [get_ports {trx0_rxdata_n_i[3]}]
set_property PACKAGE_PIN T17 [get_ports {trx0_txdata_n_o[0]}]
set_property PACKAGE_PIN N18 [get_ports {trx0_txdata_n_o[2]}]
set_property PACKAGE_PIN J17 [get_ports {trx0_txdata_n_o[4]}]
set_property PACKAGE_PIN G16 [get_ports {trx1_rxdata_n_i[0]}]
set_property PACKAGE_PIN E20 [get_ports {trx1_rxdata_n_i[2]}]
set_property PACKAGE_PIN A19 [get_ports {trx1_rxdata_n_i[4]}]
set_property PACKAGE_PIN A17 [get_ports {trx1_txdata_n_o[0]}]
set_property PACKAGE_PIN B15 [get_ports {trx1_txdata_n_o[2]}]
set_property PACKAGE_PIN A22 [get_ports {trx1_txdata_n_o[4]}]


set_property IODELAY_GROUP trx0_iodelay_grp [get_cells design_1_i/axi_serdes_fmc_0/U0/transceiver0_inst/idelayctrl_inst]
set_property IODELAY_GROUP trx0_iodelay_grp [get_cells design_1_i/axi_serdes_fmc_0/U0/transceiver0_inst/rx_interface_inst/clk_idelay_inst]
set_property IODELAY_GROUP trx0_iodelay_grp [get_cells {design_1_i/axi_serdes_fmc_0/U0/transceiver0_inst/rx_interface_inst/data[0].idelay_inst}]
set_property IODELAY_GROUP trx0_iodelay_grp [get_cells {design_1_i/axi_serdes_fmc_0/U0/transceiver0_inst/rx_interface_inst/data[1].idelay_inst}]
set_property IODELAY_GROUP trx0_iodelay_grp [get_cells {design_1_i/axi_serdes_fmc_0/U0/transceiver0_inst/rx_interface_inst/data[2].idelay_inst}]
set_property IODELAY_GROUP trx0_iodelay_grp [get_cells {design_1_i/axi_serdes_fmc_0/U0/transceiver0_inst/rx_interface_inst/data[3].idelay_inst}]
set_property IODELAY_GROUP trx0_iodelay_grp [get_cells {design_1_i/axi_serdes_fmc_0/U0/transceiver0_inst/rx_interface_inst/data[4].idelay_inst}]

set_property IODELAY_GROUP trx1_iodelay_grp [get_cells design_1_i/axi_serdes_fmc_0/U0/transceiver1_inst/idelayctrl_inst]
set_property IODELAY_GROUP trx1_iodelay_grp [get_cells design_1_i/axi_serdes_fmc_0/U0/transceiver1_inst/rx_interface_inst/clk_idelay_inst]
set_property IODELAY_GROUP trx1_iodelay_grp [get_cells {design_1_i/axi_serdes_fmc_0/U0/transceiver1_inst/rx_interface_inst/data[0].idelay_inst}]
set_property IODELAY_GROUP trx1_iodelay_grp [get_cells {design_1_i/axi_serdes_fmc_0/U0/transceiver1_inst/rx_interface_inst/data[1].idelay_inst}]
set_property IODELAY_GROUP trx1_iodelay_grp [get_cells {design_1_i/axi_serdes_fmc_0/U0/transceiver1_inst/rx_interface_inst/data[2].idelay_inst}]
set_property IODELAY_GROUP trx1_iodelay_grp [get_cells {design_1_i/axi_serdes_fmc_0/U0/transceiver1_inst/rx_interface_inst/data[3].idelay_inst}]
set_property IODELAY_GROUP trx1_iodelay_grp [get_cells {design_1_i/axi_serdes_fmc_0/U0/transceiver1_inst/rx_interface_inst/data[4].idelay_inst}]


create_clock -period 3.200 -name trx0_clk_p_i -waveform {0.000 1.600} [get_ports trx0_clk_p_i]
create_clock -period 3.200 -name trx0_rxclk_p_i -waveform {0.000 1.600} [get_ports trx0_rxclk_p_i]
create_clock -period 3.200 -name trx1_clk_p_i -waveform {0.000 1.600} [get_ports trx1_clk_p_i]
create_clock -period 3.200 -name trx1_rxclk_p_i -waveform {0.000 1.600} [get_ports trx1_rxclk_p_i]
create_generated_clock -name trx0_txclk_p_o -source [get_pins design_1_i/axi_serdes_fmc_0/U0/transceiver0_inst/tx_interface_inst/clk_oddr_inst/C] -divide_by 1 -invert [get_ports trx0_txclk_p_o]
create_generated_clock -name trx1_txclk_p_o -source [get_pins design_1_i/axi_serdes_fmc_0/U0/transceiver1_inst/tx_interface_inst/clk_oddr_inst/C] -divide_by 1 -invert [get_ports trx1_txclk_p_o]


